[youtube]
client_secrets_file = ""
credentials_file = ""

[source]
    [source."668668"]
    source_type = "huya"
    room_id = "668668"
    sticky_m3u8 = "http://aldirect.hls.huya.com/huyalive/1445831202-1445831202-6209797728126369792-3356350302-10057-A-0-1.m3u8"
    title = "风行云 - {datetime} - 录像"
    description = "直播地址：https://www.huya.com/668668"

[notifiers]
    [notifiers.telegram]
        chat_id = ""
        enabled = true
        token = ""
