[app]
debug = false
video_path = "./videos"
danmaku_path = "./videos/caption"
upload_validate = true
max_duration = 39600
max_size = "1989M"
mongo_dsn = ""
timezone = "Asia/Hong_Kong"
ffprobe_path = "ffprobe"
ffmpeg_path = "ffmpeg"
sentry_dsn = ""
save_metadata = false

[youtube]
client_secrets_file = ""
credentials_file = ""

[spankbang]
username = ""
password = ""

[telegram]
api_id = 0
api_hash = ""
string_session = ""
chat_id = 0

[huya]
app_id = ""
app_secret = ""

[panda]
sess_key = "018c6d30a09720dd7aba6a9113fa5227bc9c78e033eb1a2be5fec88af599e3c6"
max_size = "1989M"
save_metadata = false
proxy = "http://"
headers = ["Origin: https://m.pandalive.co.kr", "Referer: https://m.pandalive.co.kr/"]

[source]
[source."668668"]
enabled = true
danmaku_enabled = true
auto_upload = true
auto_upload_minimal_size = 1024
auto_upload_minimal_duration = 3600
interval = 5
source_type = "huya"
room_id = "668668"
title = "风行云 - {datetime} - 录像"
description = "直播地址：https://www.huya.com/668668"
playlist_id = "PLlph9D7YplcHhxNmhBGsgzTgLSlpk4B5-"
ws_apis = ["wss://wsapi.huya.com"]
preferred_cdn_type = "AL"
preferred_format = "flv"
ratio = "8000"
min_start_time = 140

[source."18053596"]
enabled = true
danmaku_enabled = true
auto_upload = true
auto_upload_minimal_size = 1024
auto_upload_minimal_duration = 3600
interval = 60
source_type = "huya"
room_id = "18053596"
title = "填坑小子668 - {datetime} - 录像"
description = "直播地址：https://www.huya.com/18053596"
playlist_id = "PLlph9D7YplcEZkvv6_PByv_S7TffhhP96"
ws_apis = ["wss://wsapi.huya.com"]
preferred_cdn_type = "AL"
preferred_format = "flv"
ratio = "8000"
min_start_time = 140

[source."deer98"]
enabled = false
danmaku_enabled = false
auto_upload = false
auto_upload_minimal_size = 1024
auto_upload_minimal_duration = 3600
interval = 60
source_type = "panda"
room_id = "10535725"
sess_key = "018c6d30a09720dd7aba6a9113fa5227bc9c78e033eb1a2be5fec88af599e3c6"

[notifiers]
[notifiers.telegram]
chat_id = ""
enabled = true
token = ""
