[youtube]
client_secrets_file = ""
credentials_file = ""

[source]
    [source."668668"]
    enabled = true
    auto_upload = true
    auto_upload_minimal_size = 1024
    source_type = "huya"
    room_id = "668668"
    title = "风行云 - {datetime} - 录像"
    description = "直播地址：https://www.huya.com/668668"
    ws_apis = [ "wss://0dfbdba8-ws.va.huya.com", "wss://128a4d17-ws.va.huya.com", "wss://128a9862-ws.va.huya.com" ]
    preferred_cdn_type = "AL"

    [source."deer98"]
    enabled = true
    auto_upload = false
    auto_upload_minimal_size = 1024
    source_type = "panda"
    room_id = "10535725"
    sess_key = "018c6d30a09720dd7aba6a9113fa5227bc9c78e033eb1a2be5fec88af599e3c6"

[notifiers]
    [notifiers.telegram]
        chat_id = ""
        enabled = true
        token = ""
