[youtube]
client_secrets_file = ""
credentials_file = ""

[source]
    [source."668668"]
    source_type = "huya"
    room_id = "668668"
    title = "风行云 - {datetime} - 录像"
    description = "直播地址：https://www.huya.com/668668"

[notifiers]
    [notifiers.telegram]
        chat_id = ""
        enabled = true
        token = ""
