services:
  mongo:
    image: "mongo:${MONGO_VERSION:-6.0.1}"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:-recorder}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-well_known_password}"
    ports:
      - "${MONGO_PORT:-127.0.0.1:27017}:27017"
    volumes:
      - "${MONGO_VOLUME_DATA_DB:-./mongo_data}:/data/db"
  recorder:
    build: .
    restart: always
    volumes:
      - "${RECORDER_CONFIG:-./config.toml}:/app/config.toml"
      - "${RECORDER_YOUTUBE_CLIENT_SECRETS:-./.client_secrets.json}:/app/.client_secrets.json"
      - "${RECORDER_YOUTUBE_CREDENTIALS:-./.recorder-credentials.pkl}:/app/.recorder-credentials.pkl"
      - "${RECORDER_VIDEO:-./videos}:/app/videos"
  danmaku-subscriber:
    build: .
    restart: always
    volumes:
      - "${RECORDER_CONFIG:-./config.toml}:/app/config.toml"
    environment:
      PYTHONPATH: $PYTHONPATH:/app/recorder;
    command: python3 recorder/utils/huya_danmaku_mongo.py sub
