services:
  mongo:
    image: "mongo:${MONGO_VERSION:-6.0.3}"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:-recorder}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-well_known_password}"
    ports:
      - "${MONGO_PORT:-127.0.0.1:27017}:27017"
    volumes:
      - "${MONGO_VOLUME_DATA_DB:-./mongo_data}:/data/db"
  mongo-express:
    image: "mongo-express:${MONGO_EXPRESS_VERSION:-1.0.0-alpha.4}"
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME:-recorder}:${MONGO_INITDB_ROOT_PASSWORD:-well_known_password}@mongo:27017"
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_EXPRESS_USERNAME:-recorder}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_EXPRESS_PASSWORD:-well_known_password}"
    ports:
      - "${MONGO_EXPRESS_PORT:-127.0.0.1:8081}:8081"
  recorder:
    build: .
    restart: always
    depends_on:
      - mongo
    volumes:
      - "${RECORDER_CONFIG:-./config.toml}:/app/config.toml"
      - "${RECORDER_YOUTUBE_CLIENT_SECRETS:-./.client_secrets.json}:/app/.client_secrets.json"
      - "${RECORDER_YOUTUBE_CREDENTIALS:-./.recorder-credentials.pkl}:/app/.recorder-credentials.pkl"
      - "${RECORDER_VIDEO:-./videos}:/app/videos"
  danmaku-subscriber:
    build: .
    restart: always
    depends_on:
      - mongo
    volumes:
      - "${RECORDER_CONFIG:-./config.toml}:/app/config.toml"
    environment:
      PYTHONPATH: $PYTHONPATH:/app/recorder;
    command: python3 recorder/utils/huya_danmaku_mongo.py sub
