[program:bililive-mongo-backfill]
directory=/root/recorder
command=/usr/local/bin/pipenv run python -u -m recorder.utils.bililive_mongo_backfill run
user=root
autostart=false
autorestart=false
startsecs=5
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/bililive-mongo-backfill.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=3
